// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/keyupdater/service (interfaces: ControllerKeyProvider,State,ControllerState)
//
// Generated by this command:
//
//	mockgen -package service -destination service_mock_test.go github.com/juju/juju/domain/keyupdater/service ControllerKeyProvider,State,ControllerState
//

// Package service is a generated GoMock package.
package service

import (
	context "context"

	gomock "github.com/canonical/gomock/gomock"

	machine "github.com/juju/juju/core/machine"
)

// MockControllerKeyProvider is a mock of ControllerKeyProvider interface.
type MockControllerKeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockControllerKeyProviderMockRecorder
	isgomock struct{}
}

// MockControllerKeyProviderMockRecorder is the mock recorder for MockControllerKeyProvider.
type MockControllerKeyProviderMockRecorder struct {
	mock                            *MockControllerKeyProvider
	controllerAuthorisedKeysExpects []*gomock.Call1_2[context.Context, []string, error]
}

// NewMockControllerKeyProvider creates a new mock instance.
func NewMockControllerKeyProvider(ctrl *gomock.Controller) *MockControllerKeyProvider {
	mock := &MockControllerKeyProvider{ctrl: ctrl}
	mock.recorder = &MockControllerKeyProviderMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerKeyProvider) EXPECT() *MockControllerKeyProviderMockRecorder {
	return m.recorder
}

// ControllerAuthorisedKeys mocks base method.
func (m *MockControllerKeyProvider) ControllerAuthorisedKeys(arg0 context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.controllerAuthorisedKeysExpects, m.ctrl, m, "ControllerAuthorisedKeys", arg0)
}

// ControllerAuthorisedKeys indicates an expected call of ControllerAuthorisedKeys.
func (mr *MockControllerKeyProviderMockRecorder) ControllerAuthorisedKeys(arg0 any) *MockControllerKeyProviderControllerAuthorisedKeysCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, []string, error](mr.mock.ctrl.T, mr.mock, "ControllerAuthorisedKeys", gomock.EnsureMatcher(arg0))
	mr.controllerAuthorisedKeysExpects = append(mr.controllerAuthorisedKeysExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockControllerKeyProviderControllerAuthorisedKeysCall is the typed call wrapper for ControllerAuthorisedKeys.
type MockControllerKeyProviderControllerAuthorisedKeysCall = gomock.Call1_2[context.Context, []string, error]

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock                      *MockState
	checkMachineExistsExpects []*gomock.Call2_1[context.Context, machine.Name, error]
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// CheckMachineExists mocks base method.
func (m *MockState) CheckMachineExists(arg0 context.Context, arg1 machine.Name) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_1(&m.recorder.checkMachineExistsExpects, m.ctrl, m, "CheckMachineExists", arg0, arg1)
}

// CheckMachineExists indicates an expected call of CheckMachineExists.
func (mr *MockStateMockRecorder) CheckMachineExists(arg0, arg1 any) *MockStateCheckMachineExistsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_1[context.Context, machine.Name, error](mr.mock.ctrl.T, mr.mock, "CheckMachineExists", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.checkMachineExistsExpects = append(mr.checkMachineExistsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateCheckMachineExistsCall is the typed call wrapper for CheckMachineExists.
type MockStateCheckMachineExistsCall = gomock.Call2_1[context.Context, machine.Name, error]

// MockControllerState is a mock of ControllerState interface.
type MockControllerState struct {
	ctrl     *gomock.Controller
	recorder *MockControllerStateMockRecorder
	isgomock struct{}
}

// MockControllerStateMockRecorder is the mock recorder for MockControllerState.
type MockControllerStateMockRecorder struct {
	mock                                     *MockControllerState
	namespaceForWatchControllerConfigExpects []*gomock.Call0_1[string]
}

// NewMockControllerState creates a new mock instance.
func NewMockControllerState(ctrl *gomock.Controller) *MockControllerState {
	mock := &MockControllerState{ctrl: ctrl}
	mock.recorder = &MockControllerStateMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerState) EXPECT() *MockControllerStateMockRecorder {
	return m.recorder
}

// NamespaceForWatchControllerConfig mocks base method.
func (m *MockControllerState) NamespaceForWatchControllerConfig() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.namespaceForWatchControllerConfigExpects, m.ctrl, m, "NamespaceForWatchControllerConfig")
}

// NamespaceForWatchControllerConfig indicates an expected call of NamespaceForWatchControllerConfig.
func (mr *MockControllerStateMockRecorder) NamespaceForWatchControllerConfig() *MockControllerStateNamespaceForWatchControllerConfigCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "NamespaceForWatchControllerConfig")
	mr.namespaceForWatchControllerConfigExpects = append(mr.namespaceForWatchControllerConfigExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockControllerStateNamespaceForWatchControllerConfigCall is the typed call wrapper for NamespaceForWatchControllerConfig.
type MockControllerStateNamespaceForWatchControllerConfigCall = gomock.Call0_1[string]
