// Code generated by triggergen. DO NOT EDIT.

package triggers

import (
	"fmt"

	"github.com/juju/juju/core/database/schema"
)

// ChangeLogTriggersForUserPublicSSHKey generates triggers for controller-wide
// user public SSH keys.
func ChangeLogTriggersForUserPublicSSHKey(columnName string, namespaceID int) func() schema.Patch {
	return func() schema.Patch {
		return schema.MakePatch(fmt.Sprintf(`
INSERT INTO change_log_namespace VALUES (%[2]d, 'user_public_ssh_key', 'UserPublicSSHKey changes based on %[1]s');
CREATE TRIGGER trg_log_user_public_ssh_key_insert
AFTER INSERT ON user_public_ssh_key FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (1, %[2]d, NEW.%[1]s, DATETIME('now', 'utc'));
END;
CREATE TRIGGER trg_log_user_public_ssh_key_update
AFTER UPDATE ON user_public_ssh_key FOR EACH ROW
WHEN NEW.user_uuid != OLD.user_uuid OR NEW.fingerprint != OLD.fingerprint OR NEW.public_key != OLD.public_key OR NEW.comment != OLD.comment
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (2, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;
CREATE TRIGGER trg_log_user_public_ssh_key_delete
AFTER DELETE ON user_public_ssh_key FOR EACH ROW
BEGIN
    INSERT INTO change_log (edit_type_id, namespace_id, changed, created_at)
    VALUES (4, %[2]d, OLD.%[1]s, DATETIME('now', 'utc'));
END;`, columnName, namespaceID))
	}
}
